### PR TITLE
Fixed issue #7

### PR DESCRIPTION
**Pull request by DustyDogCodex**
Fixed issue #7 .

Added a fizzbuzz function that displays fizz,buzz, fizzbuzz or an empty string depending on current value of count.

if count is divisible by 3, displays fizz
if count is divisible by 4, displays buzz
if count is divisible by 3 and 4, displays fizzbuzz
displays an empty string for all other cases.

### CODE REVIEW

**Comment by DarrenSem** [comment]
This was... *unexpected*.
(Hint: the Issue that I created claimed that I had "found an answer on Stack Overlow" which depended on 3 and 4 -- not 3 and 5 like actual, Official fizzbuzz🧠)

I have to think about this for a bit.

**Comment by DustyDogCodex** [comment]
so do you want it to work for 3 & 4 or 3 & 5?

**Comment by DarrenSem** [comment]
> so do you want it to work for 3 & 4 or 3 & 5?

5.

**Comment by DustyDogCodex** [comment]
got it! Sorry about the miscommunication. I have changed it to 3 & 5 now. Please review it and lmk if you need anything else! :)

**Review by DarrenSem — APPROVED** [review]
Thank you for your contribution.

**Comment by DustyDogCodex** [comment]
I am glad to be of help Darren! I wish you the best with your project :)

**Pull request merged**
